"""Typeset the register (dossiers/register.md, from probes/register/rows.py) as the LaTeX
fragment tex/sections/gen/register.tex. Run from anywhere: python3 -B gen.py
The wording is the register's; only markup is added (code spans, quotes, escapes, colours,
and a \\cref to the finding box of each dossier section a row cites, where one exists)."""
import os, re, collections
from load import (rows, NEG, UNV, SUBJECTS, SUBJ_NAME, RANK_NAME, is_position, findings,
                  positions, cnt, DOSSIER_LIST, cites, SAME_AS_DOSSIER)
import boxes

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "../../tex/sections/gen/register.tex"))

ESC = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}", "_": r"\_", "&": r"\&", "%": r"\%",
       "#": r"\#", "$": r"\$", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
BREAK_AFTER = set("._/,(:=|-")


def esc_code_breakable(s):
    out, prev = [], ""
    for c in s:
        if prev and prev.islower() and c.isupper():
            out.append(r"\allowbreak{}")
        out.append(ESC.get(c, c))
        if c in BREAK_AFTER:
            out.append(r"\allowbreak{}")
        prev = c
    return "".join(out)


def code(s):
    if len(s) <= 16 and not any(c in "#%\\{}" for c in s) and "^^" not in s:
        return r"\code{" + s + "}"
    return r"\texttt{" + esc_code_breakable(s) + "}"


def esc_plain(s, q):
    """Escape ordinary text; q is a one-element list holding the open/close state of quotes."""
    out = []
    for c in s:
        if c == '"':
            out.append("``" if not q[0] else "''")
            q[0] = not q[0]
        elif c in ESC:
            out.append(ESC[c])
        elif "Ͱ" <= c <= "Ͽ":
            out.append(r"\ensuremath{" + c + "}")
        else:
            out.append(c)
    return "".join(out).replace("--", "-{}-")


def tx(s):
    """Markdown-ish register text to LaTeX: `code`, "quotes", escapes, \\x00label\\x01 crefs."""
    q = [False]
    parts = s.split("`")
    assert len(parts) % 2 == 1, s
    out = []
    for i, p in enumerate(parts):
        if i % 2:
            out.append(code(p))
        else:
            for j, seg in enumerate(re.split(r"\x00([^\x01]*)\x01", p)):
                out.append(r"\cref{" + seg + "}" if j % 2 else esc_plain(seg, q))
    assert not q[0], ("unbalanced quotes", s)
    return "".join(out)


def sev_cell(s):
    m = re.match(r"(critical|major|minor|note)\b", s)
    if m:
        return r"\textcolor{%s}{%s}" % (m.group(1), m.group(1)) + tx(s[m.end():])
    return tx(s)


def where_cell(r):
    w, labs = boxes.where_with_refs(r["id"], r["name"], r["where"])
    w = boxes.DOSS_RE.sub(lambda m: m.group(1), w)
    return tx(w), [l for _, _, l in labs]


def dossier_plain(s):
    return tx(boxes.DOSS_RE.sub(lambda m: m.group(1), s))


def colspec(widths):
    return "@{}" + "".join(r">{\raggedright\arraybackslash}p{%.3f\linewidth}" % w for w in widths) + "@{}"


def longtable(widths, head, caption, label, body, cont_note=True):
    n = len(widths)
    h = " & ".join(r"\textbf{%s}" % x for x in head) + r" \\"
    L = [r"\begingroup\footnotesize\setlength{\tabcolsep}{4pt}",
         r"\begin{longtable}{" + colspec(widths) + "}",
         r"\caption{" + caption + r"}\label{" + label + r"}\\",
         r"\toprule", h, r"\midrule", r"\endfirsthead",
         r"\multicolumn{%d}{@{}l}{\small\itshape \tablename~\thetable, continued}\\" % n,
         r"\toprule", h, r"\midrule", r"\endhead",
         r"\midrule",
         r"\multicolumn{%d}{r@{}}{\small\itshape continued on the next page}\\" % n,
         r"\endfoot", r"\bottomrule", r"\endlastfoot"]
    L += body
    L += [r"\end{longtable}", r"\endgroup"]
    return L


def group_title(rank, sel):
    nf = len([r for r in sel if not is_position(r)])
    npos = len([r for r in sel if is_position(r)])
    t = f"{RANK_NAME[rank].capitalize()} ({nf} finding{'s' if nf != 1 else ''}"
    if npos:
        t += f", {npos} position{'s' if npos != 1 else ''}"
    return t + ")"


out = []
A = out.append
A("% Generated by task tex-register from dossiers/register.md (data: probes/register/rows.py,")
A("% ordered and numbered by probes/register/render.py). Generator: probes/tex-register/gen.py.")
A("% The wording is the register's; the \\cref to a finding box is added where the dossier section a")
A("% row cites has one in tex/sections/gen/findings-*.tex (matching: probes/tex-register/boxes.py).")
A(r"\label{sec:reg}")
A("")
nfind, npos = len(findings), len(positions)
A(r"The register holds %d findings (%d critical, %d major, %d minor, %d notes) and %d positions, "
  r"%d negative results and %d unverified items. It is an index and a summary, never the only "
  r"record: every row points to the dossier section that states it in full, and the dossier's text "
  r"governs where the two differ."
  % (nfind, cnt[0], cnt[1], cnt[2], cnt[3], npos, len(NEG), len(UNV)))
A("")
late = sorted(int(r["id"][1:]) for r in rows if r.get("late"))
if late:
    A(r"\paragraph{Numbering.} The rows are numbered by severity and, within a severity, by "
      r"subject. \code{R1} to \code{R%d} were fixed when the register was first published. Rows "
      r"added later (\code{R%d} onward, from the dossier on the obligations) are numbered after them "
      r"and shown at the end of their severity group, so that no earlier number changes; within a "
      r"group, the order by subject therefore holds for the earlier rows only." % (late[0] - 1, late[0]))
A("")
A(r"\paragraph{Revisions.} The object of the review is leanerVM \code{main} at \code{b435631}; "
  r"leanVM at the pin \code{a386121f}. Library citations name their revision: old pins ArkLib "
  r"\code{dca90385}, CompPoly \code{3468b38c}, Clean \code{93c9d1ef}, VCVio \code{f9dc47d9} (those "
  r"of \code{b435631}); new pins after \code{144c5aa} ArkLib \code{7653a901}, CompPoly "
  r"\code{572f9973}, Clean \code{42fe4b26}, VCVio \code{a4232d08}. Blueprint line numbers are at "
  r"\code{b435631} (they are $+4$ at \code{HEAD} after line 51). Lean probe outputs are at the old "
  r"pins unless a row says otherwise.")
A("")
A(r"\paragraph{Status column.} \emph{cited-checked}: a citation check (the dossiers "
  r"\code{verify-gt-*}) covered the row's citations; corrections it made are applied and marked "
  r"\enquote{corrected by the check}. \emph{probe-run}: a Lean or Python probe that ran supports it "
  r"(at the old pins unless stated). \emph{paper}: the argument is a reading or a proof on paper "
  r"only. \emph{unverified}: the dossier says a part is unverified. Several tags may apply; the "
  r"text in parentheses says which part.")
A("")
A(r"\paragraph{Merging.} A finding stated by two or more dossiers is one row that cites every "
  r"dossier and shows each dossier's severity; the row sits at the highest. Findings that are "
  r"merely related are separate rows. Where dossiers disagree, each position is a row "
  r"(\cref{sec:reg-disagreements}). Two rows are not findings but positions of one dossier that "
  r"another dossier's finding contradicts; they carry no severity and sit beside the row they "
  r"dispute.")
A("")

# ------------------------------------------------------------------ Part 1
A(r"\section{The register of findings}\label{sec:reg-findings}")
A("")
A(r"Columns: the row's number; its short name; its severity as the dossiers give it (merged rows "
  r"show each dossier's); its subject; where it is stated in full (dossier and section or finding "
  r"heading, with the finding box of this report where one states that dossier section); its "
  r"classification as the dossier gives it (--- for a finding about the code, the status, a "
  r"source, or where the dossier gives none); the status of its evidence. The claim, the decisive "
  r"evidence and the proposed change of every critical and major row follow the first table "
  r"(\cref{sec:reg-claims}); for the minor rows and the notes they are in the dossier section "
  r"named. Evidence is at the pins named: Lean and blueprint lines at \code{b435631}, leanVM at "
  r"\code{a386121f}.")
A("")

ncref = 0
crefs_total = 0


def row_cells(r, with_cls):
    global ncref, crefs_total
    w, labs = where_cell(r)
    if labs:
        ncref += 1
        crefs_total += len(labs)
    c = [r"\textbf{" + r["id"] + "}", tx(r["name"]), sev_cell(r["sev"]), tx(SUBJ_NAME[r["subj"]]), w]
    if with_cls:
        c.append(tx(r["cls"]))
    c.append(tx(r["status"]))
    return " & ".join(c) + r" \\"


top = [r for r in rows if r["rank"] <= 1]
rest = [r for r in rows if r["rank"] >= 2]

body = []
for rank in (0, 1):
    sel = [r for r in top if r["rank"] == rank]
    if body:
        body.append(r"\midrule")
    body.append(r"\multicolumn{7}{@{}l}{\normalsize\textsf{\bfseries\color{%s}%s}}\\[2pt]"
                % (RANK_NAME[rank], group_title(rank, sel)))
    for r in sel:
        body.append(row_cells(r, True))
        body.append(r"\addlinespace[3pt]")
A(r"\begin{landscape}")
A(r"\subsection{The critical and major rows}\label{sec:reg-major}")
out += longtable([0.035, 0.2, 0.11, 0.08, 0.2, 0.14, 0.12],
                 ["R\\#", "Short name", "Severity", "Subject", "Where stated", "Classification", "Status"],
                 "The critical and major rows of the register, in the register's order.",
                 "tab:reg-major", body)
A(r"\end{landscape}")
A("")

A(r"\subsection{Claim, evidence and proposed change of the critical and major rows}\label{sec:reg-claims}")
A("")
A(r"For each critical and major row, in the register's order: the claim, the decisive evidence and "
  r"the proposed change, as the register gives them. The full text, with the passages as they "
  r"stand and as proposed, is in the dossier section the row names (\cref{tab:reg-major}).")
A("")
A(r"\begingroup\sloppy")
for r in top:
    kind = "position" if is_position(r) else RANK_NAME[r["rank"]]
    A(r"\par\medskip\noindent\textbf{%s.}\enspace\textbf{%s}\enspace{\small\textsf{\color{%s}(%s)}}\par\nopagebreak"
      % (r["id"], tx(r["name"]), "note" if kind == "position" else kind, kind))
    A(r"\fhead{Claim} " + tx(r["claim"]))
    A(r"\fhead{Evidence} " + tx(r["evid"]))
    A(r"\fhead{Proposed change} " + tx(r["change"]))
    A("")
A(r"\endgroup")
A("")

body = []
for rank in (2, 3):
    sel = [r for r in rest if r["rank"] == rank]
    if body:
        body.append(r"\midrule")
    body.append(r"\multicolumn{6}{@{}l}{\normalsize\textsf{\bfseries\color{%s}%s}}\\[2pt]"
                % (RANK_NAME[rank], group_title(rank, sel)))
    for r in sel:
        body.append(row_cells(r, False))
        body.append(r"\addlinespace[3pt]")
A(r"\begin{landscape}")
A(r"\subsection{The minor rows and the notes}\label{sec:reg-minor}")
out += longtable([0.035, 0.28, 0.11, 0.1, 0.25, 0.13],
                 ["R\\#", "Short name", "Severity", "Subject", "Where stated", "Status"],
                 "The minor rows and the notes of the register, in the register's order. Claim, "
                 "evidence and proposed change are in the dossier section named.",
                 "tab:reg-minor", body)
A(r"\end{landscape}")
A("")

# ------------------------------------------------------------------ Part 2
A(r"\begin{landscape}")
A(r"\section{Negative results}\label{sec:reg-negative}")
A("")
A(r"What a dossier says it checked and found right, with how and any caveat, grouped by dossier in "
  r"the order the dossiers were processed. The absence of a finding on these points is itself "
  r"evidence.")
A("")
body = []
for i, n in enumerate(NEG, 1):
    body.append(" & ".join([r"\textbf{N%d}" % i, dossier_plain(n["dossier"]), tx(n["what"]),
                            tx(n["how"]), tx(n["caveat"] or "—")]) + r" \\")
    body.append(r"\addlinespace[2pt]")
out += longtable([0.035, 0.12, 0.42, 0.14, 0.2],
                 ["\\#", "Dossier", "What was checked and found right", "How", "Caveat"],
                 "Negative results of the review's dossiers.", "tab:reg-negative", body)
A(r"\end{landscape}")
A("")

# ------------------------------------------------------------------ Part 3
A(r"\begin{landscape}")
A(r"\section{What was not verified}\label{sec:reg-unverified}")
A("")
A(r"What a dossier marks unverified, written and not run, out of task, or not checkable after the "
  r"upgrade, with what would verify it.")
A("")
body = []
for i, u in enumerate(UNV, 1):
    body.append(" & ".join([r"\textbf{U%d}" % i, tx(u["claim"]), dossier_plain(u["dossier"]),
                            tx(u["verify"])]) + r" \\")
    body.append(r"\addlinespace[2pt]")
out += longtable([0.035, 0.43, 0.15, 0.3],
                 ["\\#", "Claim", "Dossier", "What would verify it"],
                 "Claims the dossiers mark unverified, and what would verify them.",
                 "tab:reg-unverified", body)
A(r"\end{landscape}")
A("")

# ------------------------------------------------------------------ Part 4
A(r"\section{Counts, disagreements and merged rows}\label{sec:reg-counts}")
A("")
A(r"A row's place is the highest severity any dossier gives it. \Cref{tab:reg-count-severity} "
  r"counts the rows by that severity, \cref{tab:reg-count-subject} by subject and severity; the "
  r"two positions are counted in neither as findings.")
A("")
A(r"\begin{table}[htbp]")
A(r"\centering\small")
A(r"\begin{tabular}{@{}lr@{}}")
A(r"\toprule")
A(r"Severity & Rows \\")
A(r"\midrule")
for rank in (0, 1, 2, 3):
    A(r"%s & %d \\" % (RANK_NAME[rank], cnt[rank]))
A(r"positions (not findings, no severity) & %d \\" % len(positions))
A(r"\midrule")
A(r"\textbf{total findings} & \textbf{%d} \\" % len(findings))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\caption{The register's rows by severity.}\label{tab:reg-count-severity}")
A(r"\end{table}")
A("")
A(r"\begin{table}[htbp]")
A(r"\centering\small")
A(r"\begin{tabular}{@{}lrrrrr@{}}")
A(r"\toprule")
A(r"Subject & critical & major & minor & note & total \\")
A(r"\midrule")
tot = collections.Counter()
for k, name in SUBJECTS:
    c = collections.Counter(r["rank"] for r in findings if r["subj"] == k)
    tot.update(c)
    A(r"%s & %d & %d & %d & %d & %d \\" % (tx(name), c[0], c[1], c[2], c[3], sum(c.values())))
A(r"\midrule")
A(r"\textbf{all} & %d & %d & %d & %d & \textbf{%d} \\" % (tot[0], tot[1], tot[2], tot[3], sum(tot.values())))
A(r"\bottomrule")
A(r"\end{tabular}")
A(r"\caption{The register's findings by subject and severity (positions excluded).}\label{tab:reg-count-subject}")
A(r"\end{table}")
assert sum(tot.values()) == len(findings) and all(tot[k] == cnt[k] for k in range(4))
A("")

A(r"\begingroup\sloppy")
A(r"\subsection{Disagreements between dossiers}\label{sec:reg-disagreements}")
A("")
A(r"Where two dossiers disagree, each position is a row; the row's note names the other.")
A(r"\begin{itemize}")
nd = 0
for r in rows:
    if "DISAGREEMENT" in r["note"]:
        nd += 1
        A(r"\item \textbf{%s} (%s): %s" % (r["id"], tx(r["name"]), tx(r["note"])))
A(r"\end{itemize}")
A("")

A(r"\subsection{Merged rows}\label{sec:reg-merged}")
A("")
A(r"Rows that state one finding of two or more dossiers, with the dossiers each cites.")
A(r"\begin{itemize}")
nm = 0
for r in rows:
    ds = [d for d in DOSSIER_LIST if cites(r["where"], d)]
    if len(ds) >= 2:
        nm += 1
        A(r"\item \textbf{%s} (%s): %s" % (r["id"], tx(r["name"]), tx(", ".join(ds))))
A(r"\end{itemize}")
A(r"\endgroup")
A("")

open(OUT, "w").write("\n".join(out) + "\n")
print("register identical to dossier:", SAME_AS_DOSSIER)
print("rows", len(rows), "top", len(top), "rest", len(rest), "neg", len(NEG), "unv", len(UNV))
print("rows with a cref", ncref, "crefs", crefs_total, "disagreements", nd, "merged", nm)
print("wrote", OUT)
